# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package1', models.CharField(max_length=1000)),
                ('package2', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='change_justification',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='If you agree, how did your perception of the support and documentation for these packages change over the course of answering these questions?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='gender',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gender?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='python_proficiency',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], max_length=100, verbose_name='How would you describe your proficiency with Python?'),
        ),
    ]
