# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_auto_20160530_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('concern', models.CharField(max_length=1000)),
                ('strategy', models.CharField(help_text='Please answer in 1 or 2 sentences.  Feel free to take a minute to think about a strategy.', max_length=10000, verbose_name='Strategy: How will you determine which package is better for this concern?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='evidence',
            field=models.CharField(blank=True, help_text='Please refer to specific information you found and pages where you found it.', max_length=10000, null=True, verbose_name='What evidence did you find to support your rating?'),
        ),
        migrations.AddField(
            model_name='question',
            name='likert_comparison_evidence',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, verbose_name="Based on the evidence you've seen, which package is better for this concern?"),
        ),
        migrations.AddField(
            model_name='question',
            name='likert_comparison_intuition',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, verbose_name='Ignoring evidence, which package do you think is actually better for this concern?'),
        ),
        migrations.AddField(
            model_name='question',
            name='likert_coverage',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, verbose_name='I was able to view all the online information relevant to this question'),
        ),
        migrations.AlterField(
            model_name='packagepair',
            name='package1',
            field=models.CharField(max_length=1000, verbose_name='What is the first package you will be learning about?'),
        ),
        migrations.AlterField(
            model_name='packagepair',
            name='package2',
            field=models.CharField(max_length=1000, verbose_name='What is the second one?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likert_confidence',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, verbose_name='How confident are you?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='strategy',
            field=models.CharField(blank=True, help_text='What documents did you look at and why?', max_length=4000, null=True, verbose_name='What was your strategy for answering this question?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL of indicator 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url1_what',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='What information on that site helped you?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url1_where',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='What web site does this URL point to?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url1_why',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Why was this helpful?'),
        ),
    ]
