# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20160531_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquestionnaire',
            name='perception_change',
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='likert_perception_change',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='My perception of the support and documentation for these packages changed over the course of answering these questions.'),
        ),
    ]
