# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20160531_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestionnaire',
            name='likert_perception_change',
            field=models.CharField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=100, null=True, verbose_name='My perception of the support and documentation for these packages changed over the course of answering these questions.'),
        ),
    ]
