# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20160531_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestionnaire',
            name='likert_perception_change',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, null=True, verbose_name='My perception of the support and documentation for these packages changed over the course of answering these questions.'),
        ),
    ]
