# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20160531_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank1',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True, verbose_name='Rank these concerns from most to least important when choosing a package.'),
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank2',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank3',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank4',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank5',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postquestionnaire',
            name='concern_rank6',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='important_concern1',
            field=models.CharField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True, verbose_name='To me, the most important question from this set when choosing a package is:'),
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='important_concern2',
            field=models.CharField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True, verbose_name='The second most important question is:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='evidence',
            field=models.CharField(blank=True, help_text="Share 1-2 sentences with links if possible.  This shouldn't take you more than 2 minutes.", max_length=10000, null=True, verbose_name='What evidence informs your rating?'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy',
            field=models.CharField(help_text="Share 1-2 sentences.  This shouldn't take you more than 2 minutes.", max_length=10000, verbose_name='What strategy will you use to find out which package is better for this concern?'),
        ),
    ]
