# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20160606_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestionnaire',
            name='concern_rank1',
            field=form.models.ConcernRankField(blank=True, choices=[(b'I will be able to find How-To documentation for all the tasks I want to do.', b'I will be able to find How-To documentation for all the tasks I want to do.'), (b'Developers will provide answers to questions I ask as fast as I need them to.', b'Developers will provide answers to questions I ask as fast as I need them to.'), (b'The documentation (e.g., API docs and example code) will reflect the most recent code.', b'The documentation (e.g., API docs and example code) will reflect the most recent code.'), (b'The community will be welcoming when they respond to questions I ask.', b'The community will be welcoming when they respond to questions I ask.'), (b"I can trust the package's developers to develop reliable, usable software.", b"I can trust the package's developers to develop reliable, usable software."), (b'The package was designed for users with my conceptual knowledge and goals.', b'The package was designed for users with my conceptual knowledge and goals.')], max_length=1000, null=True, verbose_name='Rank these concerns from most to least important when choosing a package.  Order them from top (most important) to bottom (least important).'),
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='likert_perception_change',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1, verbose_name='My perception of the quality of support and documentation for the packages has changed since the first comparison I made.'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Software developer', 'Software developer'), ('Graduate student', 'Graduate student'), ('Undergraduate student', 'Undergraduate student'), ('Project manager', 'Project manager'), ('Quality assurance', 'Quality assurance'), ('Systems administrator', 'Systems administrator'), ('Other', 'Other')], max_length=200, null=True, verbose_name='What is your job?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='programming_profiency',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], max_length=100, null=True, verbose_name='How would you describe your proficiency as a programmer?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='programming_years',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True, verbose_name='How many years of experience do you have programming?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='python_proficiency',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], max_length=100, null=True, verbose_name='How would you describe your proficiency with Python?'),
        ),
        migrations.AlterField(
            model_name='prequestionnaire',
            name='python_years',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True, verbose_name='How many years of experience do you have programming with Python or Python packages?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likert_comparison_evidence',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Based on the evidence you have seen, which package is better for this concern?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likert_confidence',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='How confident are you?'),
        ),
    ]
