# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20160606_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='na_cant_tell',
            new_name='na_likert_comparison_evidence',
        ),
    ]
