# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20160620_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestionnaire',
            name='important_concern1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='To me, the most important question from this set when choosing a package is:', choices=[({b'question': b'which package will have better How-To documentation for all the tasks you will want to do?', b'statement': b'I will find good How-To documentation for all the tasks I want to do.'}, {b'question': b'which package will have better How-To documentation for all the tasks you will want to do?', b'statement': b'I will find good How-To documentation for all the tasks I want to do.'}), ({b'question': b'for which package are other developers more likely to answer questions you ask as fast as you need them to?', b'statement': b'Other developers will answer questions I ask as fast as I need them to.'}, {b'question': b'for which package are other developers more likely to answer questions you ask as fast as you need them to?', b'statement': b'Other developers will answer questions I ask as fast as I need them to.'}), ({b'question': b"which package's documentation will be more up-to-date with the code?", b'statement': b'The documentation will be up-to-date with the code.'}, {b'question': b"which package's documentation will be more up-to-date with the code?", b'statement': b'The documentation will be up-to-date with the code.'}), ({b'question': b'which community will be more welcoming when responding to questions you ask?', b'statement': b'The community will be welcoming when they respond to questions I ask.'}, {b'question': b'which community will be more welcoming when responding to questions you ask?', b'statement': b'The community will be welcoming when they respond to questions I ask.'}), ({b'question': b"which package's developers can you better trust to make reliable, usable software?", b'statement': b'I can trust the developers of the package to make reliable, usable software.'}, {b'question': b"which package's developers can you better trust to make reliable, usable software?", b'statement': b'I can trust the developers of the package to make reliable, usable software.'}), ({b'question': b'which package was better designed for users with your technical knowledge and goals?', b'statement': b'The package was designed for users with my technical knowledge and goals.'}, {b'question': b'which package was better designed for users with your technical knowledge and goals?', b'statement': b'The package was designed for users with my technical knowledge and goals.'})]),
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='important_concern2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='The second most important question is:', choices=[({b'question': b'which package will have better How-To documentation for all the tasks you will want to do?', b'statement': b'I will find good How-To documentation for all the tasks I want to do.'}, {b'question': b'which package will have better How-To documentation for all the tasks you will want to do?', b'statement': b'I will find good How-To documentation for all the tasks I want to do.'}), ({b'question': b'for which package are other developers more likely to answer questions you ask as fast as you need them to?', b'statement': b'Other developers will answer questions I ask as fast as I need them to.'}, {b'question': b'for which package are other developers more likely to answer questions you ask as fast as you need them to?', b'statement': b'Other developers will answer questions I ask as fast as I need them to.'}), ({b'question': b"which package's documentation will be more up-to-date with the code?", b'statement': b'The documentation will be up-to-date with the code.'}, {b'question': b"which package's documentation will be more up-to-date with the code?", b'statement': b'The documentation will be up-to-date with the code.'}), ({b'question': b'which community will be more welcoming when responding to questions you ask?', b'statement': b'The community will be welcoming when they respond to questions I ask.'}, {b'question': b'which community will be more welcoming when responding to questions you ask?', b'statement': b'The community will be welcoming when they respond to questions I ask.'}), ({b'question': b"which package's developers can you better trust to make reliable, usable software?", b'statement': b'I can trust the developers of the package to make reliable, usable software.'}, {b'question': b"which package's developers can you better trust to make reliable, usable software?", b'statement': b'I can trust the developers of the package to make reliable, usable software.'}), ({b'question': b'which package was better designed for users with your technical knowledge and goals?', b'statement': b'The package was designed for users with my technical knowledge and goals.'}, {b'question': b'which package was better designed for users with your technical knowledge and goals?', b'statement': b'The package was designed for users with my technical knowledge and goals.'})]),
        ),
    ]
