# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('tab_index', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=2048)),
                ('event_type', models.CharField(max_length=128)),
            ],
        ),
    ]
