# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchlogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='url',
            field=models.CharField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='visit_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
