#! /bin/bash
ansible-playbook -i hosts main.yml --ask-pass --ask-become-pass $@\
  --extra-vars "@aws-credentials.json"\
  --extra-vars "@logger-pg-credentials.json"\
  --extra-vars "@reader-pg-credentials.json"
